updated all makefiles and build scripts. now I can happily do make CC=xxx ..., make/gmake issue should also be fixed.
git-svn-id: file:///svn/uhexen2/code/trunk@701 eaf649e6-6c13-0410-b194-84221022858e

diff --git a/utils/build b/utils/build
--- a/utils/build
+++ b/utils/build
@@ -1,17 +1,30 @@
 #!/bin/sh
 
+if [ -f /usr/local/bin/make ]; then
+	MAKE=/usr/local/bin/make
+elif [ -f /usr/bin/make ]; then
+	MAKE=/usr/bin/make
+elif [ -f /usr/local/bin/gmake ]; then
+	MAKE=/usr/local/bin/gmake
+elif [ -f /usr/bin/gmake ]; then
+	MAKE=/usr/bin/gmake
+else
+	echo "Error: make or gmake not found"
+	exit 1
+fi
+
 echo "Building hcc, the HexenC compiler.."
-make -C h2mp_utils/hcc
+$MAKE -C h2mp_utils/hcc
 echo "" && echo "Now building hcc, old version"
-make -C h2_utils/hcc
+$MAKE -C h2_utils/hcc
 echo "" && echo "Now building qfiles.."
-make -C h2mp_utils/qfiles
+$MAKE -C h2mp_utils/qfiles
 echo "" && echo "Now building genmodel.."
-make -C h2mp_utils/genmodel
+$MAKE -C h2mp_utils/genmodel
 echo "" && echo "Now building light, vis and qbsp.."
-make -C h2mp_utils/utils
+$MAKE -C h2mp_utils/utils
 echo "" && echo "Now building light, vis and qbsp, old versions.."
-make -C h2_utils/utils
+$MAKE -C h2_utils/utils
 echo "" && echo "Now building dhcc, a progs.dat decompiler.."
-make -C dcc
+$MAKE -C dcc
 
diff --git a/utils/clean b/utils/clean
--- a/utils/clean
+++ b/utils/clean
@@ -1,10 +1,23 @@
 #!/bin/sh
 
-make -C h2mp_utils/hcc clean
-make -C h2_utils/hcc clean
-make -C h2mp_utils/qfiles clean
-make -C h2mp_utils/genmodel clean
-make -C h2mp_utils/utils clean
-make -C h2_utils/utils clean
-make -C dcc clean
+if [ -f /usr/local/bin/make ]; then
+	MAKE=/usr/local/bin/make
+elif [ -f /usr/bin/make ]; then
+	MAKE=/usr/bin/make
+elif [ -f /usr/local/bin/gmake ]; then
+	MAKE=/usr/local/bin/gmake
+elif [ -f /usr/bin/gmake ]; then
+	MAKE=/usr/bin/gmake
+else
+	echo "Error: make or gmake not found"
+	exit 1
+fi
+
+$MAKE -C h2mp_utils/hcc clean
+$MAKE -C h2_utils/hcc clean
+$MAKE -C h2mp_utils/qfiles clean
+$MAKE -C h2mp_utils/genmodel clean
+$MAKE -C h2mp_utils/utils clean
+$MAKE -C h2_utils/utils clean
+$MAKE -C dcc clean
 
diff --git a/utils/h2mp_utils/build b/utils/h2mp_utils/build
--- a/utils/h2mp_utils/build
+++ b/utils/h2mp_utils/build
@@ -1,9 +1,23 @@
 #!/bin/sh
+
+if [ -f /usr/local/bin/make ]; then
+	MAKE=/usr/local/bin/make
+elif [ -f /usr/bin/make ]; then
+	MAKE=/usr/bin/make
+elif [ -f /usr/local/bin/gmake ]; then
+	MAKE=/usr/local/bin/gmake
+elif [ -f /usr/bin/gmake ]; then
+	MAKE=/usr/bin/gmake
+else
+	echo "Error: make or gmake not found"
+	exit 1
+fi
+
 echo "Building hcc, the HexenC compiler.."
-make -C hcc
+$MAKE -C hcc
 echo "" && echo "Now building qfiles.."
-make -C qfiles
+$MAKE -C qfiles
 echo "" && echo "Now building genmodel.."
-make -C genmodel
+$MAKE -C genmodel
 echo "" && echo "Now building light, vis and qbsp.."
-make -C utils
+$MAKE -C utils
diff --git a/utils/h2mp_utils/clean b/utils/h2mp_utils/clean
--- a/utils/h2mp_utils/clean
+++ b/utils/h2mp_utils/clean
@@ -1,5 +1,19 @@
 #!/bin/sh
-make -C hcc clean
-make -C qfiles clean
-make -C genmodel clean
-make -C utils clean
+
+if [ -f /usr/local/bin/make ]; then
+	MAKE=/usr/local/bin/make
+elif [ -f /usr/bin/make ]; then
+	MAKE=/usr/bin/make
+elif [ -f /usr/local/bin/gmake ]; then
+	MAKE=/usr/local/bin/gmake
+elif [ -f /usr/bin/gmake ]; then
+	MAKE=/usr/bin/gmake
+else
+	echo "Error: make or gmake not found"
+	exit 1
+fi
+
+$MAKE -C hcc clean
+$MAKE -C qfiles clean
+$MAKE -C genmodel clean
+$MAKE -C utils clean
